<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOAI1GDI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOAI1GDI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOAI1GDI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOAI1GDI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOAI1GDI\App_KernelDevDebugContainer([
    'container.build_hash' => 'OAI1GDI',
    'container.build_id' => '301d8cee',
    'container.build_time' => 1584886412,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOAI1GDI');
